-- Build 42 registers identifiers before scripts and normal Lua are loaded.
-- These hidden aliases preserve the B41 profession-trait migration path. The
-- B42 server handler converts them to their real vanilla trait on first spawn;
-- new integrations should grant the `base:` trait directly instead (see
-- docs/B42-MIGRATION.md).

ProfessionFrameworkRegistries = ProfessionFrameworkRegistries or {}
ProfessionFrameworkRegistries.SpecialTraits = ProfessionFrameworkRegistries.SpecialTraits or {}

local specialTraits = ProfessionFrameworkRegistries.SpecialTraits

specialTraits.SpeedDemon2 = CharacterTrait.register("ProfessionFramework:speeddemon2")
specialTraits.SundayDriver2 = CharacterTrait.register("ProfessionFramework:sundaydriver2")
specialTraits.BaseballPlayer2 = CharacterTrait.register("ProfessionFramework:baseballplayer2")
specialTraits.Brave2 = CharacterTrait.register("ProfessionFramework:brave2")
specialTraits.Cowardly2 = CharacterTrait.register("ProfessionFramework:cowardly2")
specialTraits.Clumsy2 = CharacterTrait.register("ProfessionFramework:clumsy2")
specialTraits.Graceful2 = CharacterTrait.register("ProfessionFramework:graceful2")
specialTraits.ShortSighted2 = CharacterTrait.register("ProfessionFramework:shortsighted2")
specialTraits.EagleEyed2 = CharacterTrait.register("ProfessionFramework:eagleeyed2")
specialTraits.HardOfHearing2 = CharacterTrait.register("ProfessionFramework:hardofhearing2")
specialTraits.Deaf2 = CharacterTrait.register("ProfessionFramework:deaf2")
specialTraits.KeenHearing2 = CharacterTrait.register("ProfessionFramework:keenhearing2")
specialTraits.HeartyAppitite2 = CharacterTrait.register("ProfessionFramework:heartyappitite2")
specialTraits.LightEater2 = CharacterTrait.register("ProfessionFramework:lighteater2")
specialTraits.ThickSkinned2 = CharacterTrait.register("ProfessionFramework:thickskinned2")
specialTraits.Thinskinned2 = CharacterTrait.register("ProfessionFramework:thinskinned2")
specialTraits.Resilient2 = CharacterTrait.register("ProfessionFramework:resilient2")
specialTraits.ProneToIllness2 = CharacterTrait.register("ProfessionFramework:pronetoillness2")
specialTraits.Dextrous2 = CharacterTrait.register("ProfessionFramework:dextrous2")
specialTraits.AllThumbs2 = CharacterTrait.register("ProfessionFramework:allthumbs2")
specialTraits.FastHealer2 = CharacterTrait.register("ProfessionFramework:fasthealer2")
specialTraits.SlowHealer2 = CharacterTrait.register("ProfessionFramework:slowhealer2")
specialTraits.FastLearner2 = CharacterTrait.register("ProfessionFramework:fastlearner2")
specialTraits.SlowLearner2 = CharacterTrait.register("ProfessionFramework:slowlearner2")
specialTraits.FastReader2 = CharacterTrait.register("ProfessionFramework:fastreader2")
specialTraits.SlowReader2 = CharacterTrait.register("ProfessionFramework:slowreader2")
specialTraits.Illiterate2 = CharacterTrait.register("ProfessionFramework:illiterate2")
specialTraits.NeedsLessSleep2 = CharacterTrait.register("ProfessionFramework:needslesssleep2")
specialTraits.NeedsMoreSleep2 = CharacterTrait.register("ProfessionFramework:needsmoresleep2")
specialTraits.Inconspicuous2 = CharacterTrait.register("ProfessionFramework:inconspicuous2")
specialTraits.Conspicuous2 = CharacterTrait.register("ProfessionFramework:conspicuous2")
specialTraits.Organized2 = CharacterTrait.register("ProfessionFramework:organized2")
specialTraits.Disorganized2 = CharacterTrait.register("ProfessionFramework:disorganized2")
specialTraits.LowThirst2 = CharacterTrait.register("ProfessionFramework:lowthirst2")
specialTraits.HighThirst2 = CharacterTrait.register("ProfessionFramework:highthirst2")
specialTraits.WeakStomach2 = CharacterTrait.register("ProfessionFramework:weakstomach2")
specialTraits.IronGut2 = CharacterTrait.register("ProfessionFramework:irongut2")
specialTraits.Outdoorsman2 = CharacterTrait.register("ProfessionFramework:outdoorsman2")
specialTraits.AdrenalineJunkie2 = CharacterTrait.register("ProfessionFramework:adrenalinejunkie2")
specialTraits.NightVision2 = CharacterTrait.register("ProfessionFramework:nightvision2")
specialTraits.Agoraphobic2 = CharacterTrait.register("ProfessionFramework:agoraphobic2")
specialTraits.Claustophobic2 = CharacterTrait.register("ProfessionFramework:claustophobic2")
specialTraits.Hemophobic2 = CharacterTrait.register("ProfessionFramework:hemophobic2")
specialTraits.Insomniac2 = CharacterTrait.register("ProfessionFramework:insomniac2")
specialTraits.Pacifist2 = CharacterTrait.register("ProfessionFramework:pacifist2")
specialTraits.Smoker2 = CharacterTrait.register("ProfessionFramework:smoker2")
specialTraits.Asthmatic2 = CharacterTrait.register("ProfessionFramework:asthmatic2")
specialTraits.Herbalist2 = CharacterTrait.register("ProfessionFramework:herbalist2")
specialTraits.Handy2 = CharacterTrait.register("ProfessionFramework:handy2")
specialTraits.Jogger2 = CharacterTrait.register("ProfessionFramework:jogger2")
